export enum TimeOfDay {
    Any = "Any",
    Nighttime = "Nighttime",
    Daytime = "Daytime",
    DuskDawn = "Dusk/Dawn"
}

export type Fish = {
    Quality: string,
    Fish: string,
    "Fishing Hole": string,
    "Open Water": boolean,
    Bait: string,
    "Time of Day": TimeOfDay,
    "Notes": string,
    "Location": string,
    "Achieve": string,
    "Achieve Order": string
}

export abstract class FishData {
    public static getFishByName(name: string) : Fish | undefined {
        //TODO: Improve performance with HashMap or sth

        return fishLookup[name];
    }
}



const fish : Fish[] = [
    {
        "Quality": "Gray",
        "Fish": "Broken Trident",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Any",
        "Achieve": "Aquatic Trash Collector",
        "Achieve Order": "6"
    },
    {
        "Quality": "Gray",
        "Fish": "Tarnished Brass Compass",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Any",
        "Achieve": "Aquatic Treasure Collector",
        "Achieve Order": "1"
    },
    {
        "Quality": "Gray",
        "Fish": "Tarnished Bronze Astrolabe",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Any",
        "Achieve": "Aquatic Treasure Collector",
        "Achieve Order": "3"
    },
    {
        "Quality": "White",
        "Fish": "Globefish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Bluefin Trevally",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Cherry Salmon",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Cutlass Fish",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Stingray",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Spotted Stingray",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Fugu Fish",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Mullet",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Corvina",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Crimson Snapper",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Honeycomb Grouper",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Humphead Wrasse",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Skipjack Tuna",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Sailfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Porgy",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Chestnut Sea Bream",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Green Sawfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Tripletail",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Dragonet",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Mega Prawn",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Sunfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Seitung Province",
        "Achieve": "Seitung Province Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Flying Fish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Blowfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Emerald Snapper",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Amberjack",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Blue Dorado",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Giant Trevally",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Bluefin Tuna",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Pollock",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Emperor Fish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Kahawai",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Pufferfish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Sturgeon",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Tarpon",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Swordfish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Sea Perch",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Weever",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Striped Barracuda",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Dragonfish",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Taimen",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Starry Flounder",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Oarfish",
        "Fishing Hole": "Channel Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "New Kaineng City",
        "Achieve": "Kaineng Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Freshwater Eel",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Black Carp",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Bullhead Catfish",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Cherry Barb",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Amber Trout",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Royal Featherback",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Melandru's Lurker",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Stone Loach",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Knifefish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Snakehead",
        "Fishing Hole": "Grotto Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Petrifish",
        "Fishing Hole": "Grotto Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Albino Gourami",
        "Fishing Hole": "Grotto Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Albino Axolotl",
        "Fishing Hole": "Grotto Fish",
        "Open Water": false,
        "Bait": "Glow Worms",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Dark Sleeper",
        "Fishing Hole": "Grotto Fish",
        "Open Water": false,
        "Bait": "Glow Worms",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Echovald Wilds",
        "Achieve": "Echovald Wilds Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Boxfish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Canthan Carp",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Jade Lamprey",
        "Fishing Hole": "Quarry Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Spotted Pufferfish",
        "Fishing Hole": "Quarry Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Giant Gourami",
        "Fishing Hole": "Quarry Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Jade Sea Turtle",
        "Fishing Hole": "Quarry Fish",
        "Open Water": false,
        "Bait": "Nightcrawlers",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Cuttlefish",
        "Fishing Hole": "Quarry Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Rohu",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Gourami",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Toadfish",
        "Fishing Hole": "Cavern Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Sheatfish",
        "Fishing Hole": "Cavern Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Unicorn Fish",
        "Fishing Hole": "Cavern Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Axolotl",
        "Fishing Hole": "Cavern Fish",
        "Open Water": false,
        "Bait": "Nightcrawlers",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Chambered Nautilus",
        "Fishing Hole": "Cavern Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Dragon's End",
        "Achieve": "Dragon's End Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "Gray",
        "Fish": "Goldfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Yellow",
        "Fish": "Armored Scalefish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Yellow",
        "Fish": "Bloodfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Bonefish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Yellow",
        "Fish": "Clawfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Yellow",
        "Fish": "Dustfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Orange",
        "Fish": "Sunscale Striker",
        "Fishing Hole": "Any",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "Gray",
        "Fish": "Silverfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Gray",
        "Fish": "Red Herring",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Yellow",
        "Fish": "Fangfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Totemfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Yellow",
        "Fish": "Venomfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Orange",
        "Fish": "Twilight Striker",
        "Fishing Hole": "Any",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Orange",
        "Fish": "Moonfin Striker",
        "Fishing Hole": "Any",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "World Class Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Bitterling",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Bluegill",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Rock Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Largemouth Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Golden Trout",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Gar",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Muskellunge",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Bream",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Brook Trout",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Catfish",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Rainbow Trout",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Ripsaw Catfish",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Giant Catfish",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Old Whiskers",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "Release for 2500 karma",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Cutthroat Trout",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Smallmouth Bass",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Black Crappie",
        "Fishing Hole": "Noxious Water Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Yellow Perch",
        "Fishing Hole": "Noxious Water Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Warmouth",
        "Fishing Hole": "Noxious Water Fish",
        "Open Water": false,
        "Bait": "Lightning Bugs",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Aquatic Frog",
        "Fishing Hole": "Noxious Water Fish",
        "Open Water": false,
        "Bait": "Lightning Bugs",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Release for 1500 karma",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Branded Eel",
        "Fishing Hole": "Noxious Water Fish",
        "Open Water": false,
        "Bait": "Lightning Bugs",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ascalon",
        "Achieve": "Ascalonian Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Elonian Bass",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Blue",
        "Fish": "Elon Tetra",
        "Fishing Hole": "Desert Fish",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Green",
        "Fish": "Barramundi",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Yellow",
        "Fish": "Giant Barb",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Orange",
        "Fish": "Gilded Loach",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Pink",
        "Fish": "Marbled Lungfish",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Scorpions",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Purple",
        "Fish": "Giant Paddlefish",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "White",
        "Fish": "Mahseer",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Blue",
        "Fish": "Lungfish",
        "Fishing Hole": "Desert Fish",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Green",
        "Fish": "Red-Eyed Piranha",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Yellow",
        "Fish": "Mudskipper",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Orange",
        "Fish": "Golden Mahseer",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Pink",
        "Fish": "Striped Catfish",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Scorpions",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Purple",
        "Fish": "Kaluga",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "White",
        "Fish": "Tilapia",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Blue",
        "Fish": "Zander",
        "Fishing Hole": "Desert Fish",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Green",
        "Fish": "Sand Carp",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Yellow",
        "Fish": "Paddlefish",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Orange",
        "Fish": "Silver Bichir",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Pink",
        "Fish": "Tigerfish",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "Purple",
        "Fish": "Vundu",
        "Fishing Hole": "Desert Fish",
        "Open Water": false,
        "Bait": "Scorpions",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Elon River",
        "Achieve": " Crystal Desert",
        "Achieve Order": " Elonian Mainland\""
    },
    {
        "Quality": "White",
        "Fish": "Sea Trout",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Cobia",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Diamond Trevally",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Yellowtail Snapper",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Pompano",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "King Crab",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Beluga",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Sheepshead",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Parrotfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Roosterfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Opah",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Wahoo",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Blue Marlin",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Mackerel",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Dandan",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Isles of Elona",
        "Achieve": "Desert Isles Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Krytan Crawfish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Delavan Guppy",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Steelhead Trout",
        "Fishing Hole": "River Fish",
        "Open Water": false,
        "Bait": "Fish Eggs",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Croaker",
        "Fishing Hole": "River Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Divinity Angelfin",
        "Fishing Hole": "River Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Queenfish",
        "Fishing Hole": "River Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Mud Skate",
        "Fishing Hole": "River Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Speckled Perch",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Round Goby",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Striped Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Black Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Quagmire Eel",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Royal Pike",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Slaughterfish",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Minnows",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Spotted Flounder",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Sailfin Molly",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Swampblight Lamprey",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Silver Moony",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Krytan Puffer",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Holy Mackerel",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Black Lionfish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Kryta",
        "Achieve": "Krytan Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Brackish Goby",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Oscar",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Bicuda",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Pacu",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Arowana",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Golden Dorado",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Sparkfly Larvae",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Arapaima",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Sparkfly Larvae",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Piranha",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Silver Drum",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Payara",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Peacock Bass",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Sardinata",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Jundia",
        "Fishing Hole": "Freshwater Fish",
        "Open Water": false,
        "Bait": "Sparkfly Larvae",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Goliath Grouper",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Snook",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Surubim",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Maguuma Trout",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Wolffish",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Maguuma Jack",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Rainbow Glowfish",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Royal Starfish",
        "Fishing Hole": "Saltwater Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "Release for 2500 karma",
        "Location": "Maguuma Jungle",
        "Achieve": "Maguuma Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Dusky Grouper",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Albino Blindfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "Viperfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Abyssal Squid",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Stargazer",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Blobfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Leeches",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Benthic Behemoth",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Leeches",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Ghostfish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Dead Alewife",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Hagfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Spectral Jellyfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Orrian Anglerfish",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Giant Octopus",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Shipwreck Moray",
        "Fishing Hole": "Offshore Fish",
        "Open Water": false,
        "Bait": "Sardines",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Murkwater Darter",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Monkfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Dhuum Fish",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Frilled Shark",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Man-of-War",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Risen Sea Bass",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Leeches",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Unholy Mackerel",
        "Fishing Hole": "Shore Fish",
        "Open Water": false,
        "Bait": "Leeches",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Orr",
        "Achieve": "Orrian Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "White",
        "Fish": "Volcanic Blackfish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Blue",
        "Fish": "Flayfin",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Green",
        "Fish": "Garnet Ram",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Yellow",
        "Fish": "Fire Eel",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Orange",
        "Fish": "Glowing Coalfish",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Pink",
        "Fish": "Magma Ray",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": false,
        "Bait": "Lava Beetles",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "Purple",
        "Fish": "Stone Guiyu",
        "Fishing Hole": "Volcanic Fish",
        "Open Water": false,
        "Bait": "Lava Beetles",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "\"Draconis Mons",
        "Achieve": " Fireheart Rise\"",
        "Achieve Order": "Ring of Fire Fisher"
    },
    {
        "Quality": "White",
        "Fish": "Firemouth",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Igneous Rockfish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Redtail Catfish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Geyser Batfin",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Flamefin Betta",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Scorpion Fish",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Lava Beetles",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Dunkleosteus",
        "Fishing Hole": "Coastal Fish",
        "Open Water": false,
        "Bait": "Lava Beetles",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Ember Bay",
        "Achieve": "Ring of Fire Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "Yellow",
        "Fish": "Seahorse",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Release for 350 karma",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Yellow",
        "Fish": "Leafy Sea Dragon",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Release for 350 karma",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Yellow",
        "Fish": "Mantis Shrimp",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Electric Eel",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Yellow",
        "Fish": "Rockfish",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Orange",
        "Fish": "Horseshoe Crab",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Orange",
        "Fish": "Sea Robin",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "Yellow",
        "Fish": "Redfin Barb",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Yellow",
        "Fish": "Googly-Eyed Squid",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Yellow",
        "Fish": "Shimmering Squid",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "Vampire Squid",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Yellow",
        "Fish": "Flapjack Octopus",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Release for 350 karma",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Orange",
        "Fish": "Aurelian Herring",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Orange",
        "Fish": "Red Gurnard",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Saltwater",
        "Achieve": "Saltwater Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Alewife",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "1"
    },
    {
        "Quality": "Blue",
        "Fish": "Alpine Char",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "2"
    },
    {
        "Quality": "Green",
        "Fish": "White Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "3"
    },
    {
        "Quality": "Yellow",
        "Fish": "Sockeye",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "4"
    },
    {
        "Quality": "Orange",
        "Fish": "Chain Pickerel",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "5"
    },
    {
        "Quality": "Pink",
        "Fish": "Cerulean Salamander",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Ramshorn Snails",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "Release for 1500 karma",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "6"
    },
    {
        "Quality": "Purple",
        "Fish": "Glacial Snakehead",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "7"
    },
    {
        "Quality": "White",
        "Fish": "Icefish",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "8"
    },
    {
        "Quality": "Blue",
        "Fish": "Grayling",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "9"
    },
    {
        "Quality": "Green",
        "Fish": "Northern Pike",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "10"
    },
    {
        "Quality": "Yellow",
        "Fish": "King Salmon",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "11"
    },
    {
        "Quality": "Orange",
        "Fish": "Beacon's Perch",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "12"
    },
    {
        "Quality": "Pink",
        "Fish": "Lornar's Bass",
        "Fishing Hole": "Lake Fish",
        "Open Water": false,
        "Bait": "Ramshorn Snails",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "13"
    },
    {
        "Quality": "Purple",
        "Fish": "Alabaster Oscar",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Ramshorn Snails",
        "Time of Day": TimeOfDay.Daytime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "14"
    },
    {
        "Quality": "White",
        "Fish": "Snow Crab",
        "Fishing Hole": "None",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "15"
    },
    {
        "Quality": "Blue",
        "Fish": "Walleye",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "16"
    },
    {
        "Quality": "Green",
        "Fish": "Boreal Cod",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "17"
    },
    {
        "Quality": "Yellow",
        "Fish": "Icy Lumpfish",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "18"
    },
    {
        "Quality": "Orange",
        "Fish": "Mystic Remora",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.DuskDawn,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "19"
    },
    {
        "Quality": "Pink",
        "Fish": "Snowflake Eel",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Ramshorn Snails",
        "Time of Day": TimeOfDay.Nighttime,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "20"
    },
    {
        "Quality": "Purple",
        "Fish": "Halibut",
        "Fishing Hole": "Boreal Fish",
        "Open Water": false,
        "Bait": "Shrimplings",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Shiverpeaks",
        "Achieve": "Shiverpeaks Fisher",
        "Achieve Order": "21"
    },
    {
        "Quality": "Gray",
        "Fish": "Rusted Brass Compass",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "1"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken Brass Spyglass",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "2"
    },
    {
        "Quality": "Gray",
        "Fish": "Rusted Bronze Astrolabe",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "3"
    },
    {
        "Quality": "Gray",
        "Fish": "Antique Diving Helm",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "4"
    },
    {
        "Quality": "Gray",
        "Fish": "Golden Merlion Statuette",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "5"
    },
    {
        "Quality": "Gray",
        "Fish": "Antique Porcelain Vase",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "6"
    },
    {
        "Quality": "Gray",
        "Fish": "Tarnished Silver Sextant",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Treasure Collector",
        "Achieve Order": "7"
    },
    {
        "Quality": "Gray",
        "Fish": "Pockmarked Vase",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "1"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken Bottle",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "2"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken Fishing Hook",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "3"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken Oar",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "4"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken Fishing Rod",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "5"
    },
    {
        "Quality": "Gray",
        "Fish": "Broken T rident",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "6"
    },
    {
        "Quality": "Gray",
        "Fish": "Shattered Fishing Cage",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "7"
    },
    {
        "Quality": "Gray",
        "Fish": "Crumbled Ancient Statue",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "8"
    },
    {
        "Quality": "Gray",
        "Fish": "Piece of Driftwood",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "9"
    },
    {
        "Quality": "Gray",
        "Fish": "Rotten Fish Head",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "10"
    },
    {
        "Quality": "Gray",
        "Fish": "Fish-Shaped Stone",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "11"
    },
    {
        "Quality": "Gray",
        "Fish": "Weathered Peg Leg",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "12"
    },
    {
        "Quality": "Gray",
        "Fish": "Rusted Mechanism",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "13"
    },
    {
        "Quality": "Gray",
        "Fish": "Tangled Net",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "",
        "Location": "Anywhere",
        "Achieve": "Oceanic Trash Collector",
        "Achieve Order": "14"
    },
    {
        "Quality": "Blue",
        "Fish": "Mackerel",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Used as bait",
        "Location": "Saltwater",
        "Achieve": "",
        "Achieve Order": ""
    },
    {
        "Quality": "Blue",
        "Fish": "Daijun Blackfin",
        "Fishing Hole": "Any",
        "Open Water": true,
        "Bait": "Haiju Minnows",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Used for Daijun Bay renown heart",
        "Location": "Seitung Province",
        "Achieve": "",
        "Achieve Order": ""
    },
    {
        "Quality": "Blue",
        "Fish": "Shinota Blackfin",
        "Fishing Hole": "Special Fishing Hole",
        "Open Water": false,
        "Bait": "Any",
        "Time of Day": TimeOfDay.Any,
        "Notes": "Used for Shinota Shore renown heart",
        "Location": "Seitung Province",
        "Achieve": "",
        "Achieve Order": ""
    }
];

const fishLookup = fish.reduce(function (aggregation, currentFish) {
    if(currentFish) {
        const name = currentFish.Fish;
        aggregation[name] = currentFish;
    }
    return aggregation;
}, Object.create(null));